# Generated by Django 3.0.7 on 2020-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_vid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.CharField(default='000', max_length=1000),
            preserve_default=False,
        ),
    ]
